### ISSUE TITLE
Support unmarshal without struct

### ISSUE THREAD

**Issue by at-wat** [at-wat/ebml-go#120]
return `map[string]interface{}`  like `encoding/json`

**Comment by nerg4l** [comment]
Hello,

When unmarshalling a `nil` map causes panic `assignment to entry in nil map`. This means I have to initialise it before hand.

OK:

```
	ret := map[string]interface{}{}
	if err := ebml.Unmarshal(r, &ret); err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}
```

Not OK:

```
	var ret map[string]interface{}
	if err := ebml.Unmarshal(r, &ret); err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}
```

Lastly, it might inly relates to matroska but `test5.mkv` from https://github.com/Matroska-Org/matroska-test-files#test-files panics `reflect.Set: value of type []uint8 is not assignable to type uint8`.

**Comment by at-wat** [comment]
```go
	var ret map[string]interface{}
	if err := ebml.Unmarshal(r, &ret); err != nil {
```
is equivalent of
```go
	if err := ebml.Unmarshal(r, nil); err != nil {
```
so I think it's invalid anyway.

`encoding/json.Unmarshal` in Go stdlib also don't support unmarshaling to nil map.
https://play.golang.org/p/zoXxUqVOAnT

But it's better to return error instead of causing panic.

**Comment by nerg4l** [comment]
Note: The two example is not equivalent. Both variable has `nil` value but their type is different.

```
	var ret map[string]interface{}
	fmt.Println(reflect.TypeOf(ret)) // output: map[string]interface {}
	fmt.Println(reflect.TypeOf(nil)) // output: <nil>
```

https://play.golang.org/p/HNYuND4iEdQ
