### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by masterada** [at-wat/ebml-go#127]
Hi!

We have a similar project. The current status of the project is that we can save opus and vp8 into a webm file, which is correctly processed by ffmpeg, however I belive there are some issues when opening the file with vlc. We planned to opensource it once we got it working beyond our basic needs, which of course never happened :) 

I made it public so you can use it if you want. One important aspect of it is the ebml nodes are generated from the official documentation (https://matroska.org/technical/specs/index.html), which means all mkv nodes are supported.

See: https://gitlab.com/proemergotech-public/webm-formatter

For the ebml node generation, see:
https://gitlab.com/proemergotech-public/webm-formatter/-/blob/master/tools/gen.go
https://gitlab.com/proemergotech-public/webm-formatter/-/blob/master/webm/const_gen.go
https://gitlab.com/proemergotech-public/webm-formatter/-/blob/master/webm/formatter_gen.go

**Comment by at-wat** [comment]
Thanks for your information.
