### ISSUE TITLE
Implement BlockReader

### ISSUE THREAD

**Issue by at-wat** [at-wat/ebml-go#128]

**Comment by tarrencev** [comment]
@at-wat i'm having issues reading webm files created with `SimpleBlockWriter` using https://github.com/ebml-go/webm.

I feel like the solution is to implement a corresponding `SimpleBlockReader` here. I would be happy to work on it. Do you have any suggestions on how it should look?

**Comment by at-wat** [comment]
#129 seems almost good. I added some API design related suggestions.

**Comment by at-wat** [comment]
BlockReader is implemented by #150.
