### ISSUE TITLE
Files not seekable

### ISSUE THREAD

**Issue by jech** [at-wat/ebml-go#134]
Galène (jech/galene) uses this package for saving videos to disk.  It appears that the files are not terminated correctly:

  * when played back in a web browser or a media player, the files are not seekable;
  * mediainfo reports that the files are truncated.

Is this an intrinsic limitation of the library, or am I doing something wrong?

**Comment by at-wat** [comment]
To make seekable webm, `SeekHead` element (which contains position of `Info`/`Track`/`Cues` elements) must be put in front of the Segment.
And `Cues` element must contain video keyframes information and should be put before `Cluster`s.
(https://www.webmproject.org/docs/container/#muxer-guidelines)

It usually requires two-pass processing as the contents of `SeekHead` and `Cues` are not deterministic at the point of writing them.
There is an implementation to make webm seekable (TypeScript): https://github.com/legokichi/ts-ebml#try-to-convert-a-mediarecorder-webm-to-seekable-webm
You can implement similar process using ebml-go. (My company internally has it.)

**Comment by jech** [comment]
Thanks for the info, that's clear.

What about mediainfo indicating that the file is truncated?

**Comment by at-wat** [comment]
I don't know what mediainfo is actually saying, but I guess it says data size of `Segment` and `Cluster` elements are unknown. (https://github.com/ietf-wg-cellar/ebml-specification/blob/master/specification.markdown#unknown-data-size)
As `webm.NewSimpleBlockWriter()` is designed to use `io.WriteCloser` (without seek), size of `Segment` and `Cluster`s are unknown when the size header is written to the stream.
To make webm seekable for all player, these data sizes must be known value.

**Comment by jech** [comment]
Thanks a lot for your explanations.  May I suggest that all of this should be documented.
